table: student_info
desc: 学生信息
fields:
    - name: id
      desc: 主键id
      type: long

    - name: student_name
      desc: 姓名
      type: string

    - name: student_weight
      desc: 体重
      type: float

    - name: create_time
      desc: 创建时间
      type: time

    - name: update_time
      desc: 更新时间
      type: time